---
baseurl: "https://patrick.wagstrom.net/"
title: "patrick dot wagstrom dot net"
languageCode: "en-us"

menu:
  main:
  - identifier: Blog
    name: Blog
    url: /weblog/
    weight: -100

ignoreFiles:
  - resume/\\.*

# Enable unsafe rendering for complicated pages
markup:
  goldmark:
    renderer:
      unsafe: true
    
params:
  subtitle: "The Internet's #3 Site for Information on Patrick Wagstrom"
  author: "Patrick Wagstrom <patrick@wagstrom.net>"
  github: "https://github.com/pridkett"
  youtube: "http://www.youtube.com/user/pridkett/videos"
  stackoverflow: "http://stackoverflow.com/users/57626/pridkett"
  stackexchange: "http://stackexchange.com/users/23095/pridkett"
  linkedin: "http://www.linkedin.com/in/pwagstrom"
  location: "Connecticut"
  githubrepo: "https://github.com/pridkett/patrick.wagstrom.net/"
  theme:
    inverse: true
    name: "superhero"
  strings:
    home_link: "<i class=\"fa fa-home\"></i> Patrick Wagstrom"
  commentsengine: intensedebate
  commentsaccount: de6c2d3e38f6fdb9bf16fa9f1904f35d
  commentsmapping:
    "/weblog/2003/05/23/lpdforfunandmp3playing/": "60"
    "/weblog/2008/01/03/goodbye-openbsd/": "110"
    "/weblog/2007/12/06/open-source-screencasting/": "153"
    "/weblog/2006/03/15/full-screen-emacs/": "203"
    "/weblog/2005/03/07/alphacentauri/": "213"
    "/weblog/2005/08/26/tvlicenses/": "217"
    "/weblog/2006/01/18/google-xslt-trickery/": "230"
    "/weblog/2007/11/28/christmas-name-drawing/": "297"
    "/weblog/2007/09/27/grandr-public-git-repo/": "322"
    "/weblog/2008/01/09/about-me/": "337"
    "/weblog/2008/02/05/disappointed-in-google/": "339"
    "/weblog/2008/02/07/who-owns-open-source/": "340"
    "/weblog/2008/02/15/political-telemarketers-or-scammers/": "341"
    "/weblog/2008/02/15/vmware-time-synchronization/": "342"
    "/weblog/2008/02/19/ds-ram-fail/": "343"
    "/weblog/2008/04/27/seamless-virtualization/": "346"
    "/weblog/2008/12/11/why-mythtv-022-will-rock-you/": "495"
    "/weblog/2003/10/31/hidingpyblosxomwithmodrewrite/": "144"
    "/weblog/2009/02/05/confusion-abounds-dtv-transition-delayed-until-june-12-or-is-it/": "658"
    "/weblog/2009/03/20/drobo-as-primary-storage-considered-harmful/": "687"
    "/weblog/2003/11/08/vpn/": "211"
    "/weblog/2009/04/02/iron-april-2009/": "718"
    "/weblog/2006/07/29/tracks-behind-apache/": "231"
    "/weblog/2009/05/08/simple-full-disk-image-backups-with-dd/": "729"
    "/weblog/2009/01/21/simple-script-to-clean-up-your-mp3-directory/": "619"
    "/weblog/2009/12/28/what-the-tsa-has-is-a-failure-to-communicate/": "804"
    "/weblog/2005/11/15/dstat-for-fun-and-profit/": "179"
    "/weblog/2010/03/03/acm-sigs-style-for-zotero/": "861"
    "/weblog/2010/11/24/do-the-tsa-new-ait-body-scanners-hurt-more-than-they-help/": "872"
    "/weblog/2006/08/07/free-isnt-free-enough/": "242"
    "/weblog/2003/05/22/ipv6applications/": "66"
    "/weblog/2011/05/10/raid-1-performance-on-windows-7/": "963"
    "/weblog/2011/09/22/graph-databases-and-revision-history/": "994"
    "/weblog/2009/03/24/safely-migrating-recordings-in-mythtv/": "/weblog/?p=709"
    "/weblog/2005/09/22/hurricaneritagoogleearth/": "/wp/?p=21"
    "/weblog/2010/02/04/command-line-updating-pages-on-google-sites/": "/weblog/?p=835"
    "/weblog/2011/04/18/guilty-pleasures/": "/weblog/?p=958"
    "/weblog/2011/11/10/guilt-motivation-and-procrastination/": "/weblog/?p=1054"

  relativePaths: true
  resumeShowPhone: false

theme: "hugo-theme-patrick-custom"
