SITE_TITLE: My Delusional Dream
HOME_URL: '/weblog/'
SITE_URL: 'http://patrick.wagstrom.net'

POST_DIR:
  - posts
#  - archives

POST_TIMEZONE: 'America/New_York'

PUBLISH_DRAFTS: no

THEME_SETTINGS:
  # typekit_id: lvr3vky
  twitter_id: pridkett
  tweet_count: 4
  #typekit_id: vty2qol
  comments: intensedebate
  comments_account: de6c2d3e38f6fdb9bf16fa9f1904f35d

PREPROCESS_LESS: no
DEBUG: no

THEME: pwagstro

ROLLUP_PAGE_SIZE: 10

