---
baseurl: "https://patrick.wagstrom.net/"
title: "patrick dot wagstrom dot net"
languageCode: "en-us"
googleAnalytics: "UA-3441054-1"

menu:
  main:
  - identifier: blog
    name: blog
    url: /weblog/
    weight: -100
  - identifer: resume
    name: resume
    url: /resume/
    weight: -100
  - identifier: research
    name: research
    url: /research/
    weight: -100
  - identifier: publications
    name: publications
    url: /publications/
    weight: -100
    
params:
  subtitle: "The Internet's #3 Site for Information on Patrick Wagstrom"
  author: "Patrick Wagstrom <patrick@wagstrom.net>"
  github: "https://github.com/pridkett"
  twitter: "https://twitter.com/pridkett"
  facebook: "https://facebook.com/patrick.wagstrom/"
  youtube: "http://www.youtube.com/user/pridkett/videos"
  stackoverflow: "http://stackoverflow.com/users/57626/pridkett"
  stackexchange: "http://stackexchange.com/users/23095/pridkett"
  linkedin: "http://www.linkedin.com/in/pwagstrom"
  location: "Connecticut"
  githubrepo: "https://github.com/pridkett/patrick.wagstrom.net/"
  theme:
    inverse: true
    name: "superhero"
  strings:
    home_link: "<i class=\"fa fa-home\"></i> Patrick Wagstrom"
  commentsEngine: intensedebate
  commentsAccount: de6c2d3e38f6fdb9bf16fa9f1904f35d
  relativePaths: true
  resumeShowPhone: false
