name: Compile and Publish Weblog

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clean build directory
      run: rm -rf public

    - name: Clean cache directory
      run: rm -rf resources

    - name: Checkout
      uses: actions/checkout@v1

    - name: Checkout Theme
      uses: srt32/git-actions@v0.0.3
      with:
        args: mkdir -p themes && cd themes && git clone https://github.com/pridkett/hugo-theme-patrick-custom

    - name: Hugo Build
      uses: srt32/hugo-action@v0.0.3
      with:
        args: --theme=hugo-theme-patrick-custom --ignoreCache

    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avz
        path: public
        remote_path: ${{ secrets.RSYNC_SERVER_DESTINATION }}
        remote_port: ${{ secrets.RSYNC_SERVER_PORT }}
        remote_host: ${{ secrets.RSYNC_SERVER_HOST }}
        remote_user: ${{ secrets.RSYNC_USERNAME }}
        remote_key: ${{ secrets.RSYNC_SERVER_SSH_KEY }}
