name: Compile and Publish Weblog

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clean build directory
      run: rm -rf public

    - name: Clean cache directory
      run: rm -rf resources

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.102.3'
        extended: true

    - run: hugo

    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avz
        path: public
        remote_path: ${{ secrets.RSYNC_SERVER_DESTINATION }}
        remote_port: ${{ secrets.RSYNC_SERVER_PORT }}
        remote_host: ${{ secrets.RSYNC_SERVER_HOST }}
        remote_user: ${{ secrets.RSYNC_USERNAME }}
        remote_key: ${{ secrets.RSYNC_SERVER_SSH_KEY }}
